import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { DirectionProvider } from "@/components/ui/direction";
import { amiri, ibmArabic, lora } from "./fonts";
import LanguageSwitcher from "@/components/ux/i18n-switcher";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
  auth
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
  auth : React.ReactNode;
}>) {
  const locale = useLocale();
  const direction = locale === "ar" ? 'rtl' : 'ltr'
  return (
    <html
      // lang={locale} 
      className={cn("h-full", "antialiased", lora.variable, amiri.variable, ibmArabic.variable, 'font-classic')}
    >
      <NextIntlClientProvider >
        <DirectionProvider dir={direction}>
          {/* {children} */}
          {/* Your app content */}
          <body  dir={direction} className={cn(amiri.className, 'bg-muted')}>
          {/* <LanguageSwitcher /> */}
            {/* <nav>
              <Link href="/login">Open modal</Link>
            </nav> */}
            {auth}
            {children}
            {modal}
            
            {/* <div>{children}</div> */}
          </body>
        </DirectionProvider>
      </NextIntlClientProvider>
    </html>
  );
}
